import { ArrowRight, Check, CreditCard } from "lucide-react";
import { Container } from "@/components/layout/container";
import { ButtonLink } from "@/components/ui/button";

const brands = [
  { name: "Ton", desc: "Sem aluguel e com planos para diferentes perfis de venda.", items: ["Tabela por modalidade", "Conta digital", "Condições conforme o plano"], href: "/go/ton", label: "Consultar condições da Ton" },
  { name: "Mercado Pago", desc: "Conta, maquininha e ecossistema integrado para negócios.", items: ["Conta digital", "Recebimento por Pix", "Point, Tap e link de pagamento"], href: "/go/mercadopago", label: "Consultar condições do Mercado Pago" },
  { name: "InfinitePay", desc: "Tecnologia e praticidade para vendas presenciais e online.", items: ["Recebimento rápido", "InfiniteTap", "Conta digital"], href: "/go/infinitepay", label: "Consultar condições da InfinitePay" },
  { name: "PagBank", desc: "Soluções de pagamento e serviços financeiros para empresas.", items: ["Maquininhas variadas", "Conta digital", "Plano Super Max"], href: "/go/pagbank", label: "Consultar condições do PagBank" },
];

export default function Page() {
  return <section className="relative py-16 sm:py-24"><div className="tech-grid"/><Container className="relative"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-400">Comparação imparcial</p><h1 className="mt-4 max-w-3xl text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">Compare maquininhas para o <span className="bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">seu negócio</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">Compare recursos, modalidades e condições sem classificação editorial. Confirme taxas e preços no site oficial antes da contratação.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{brands.map(b=><article key={b.name} className="glass relative overflow-hidden rounded-3xl p-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h2 className="text-2xl font-bold">{b.name}</h2></div><p className="mt-4 max-w-md leading-7 text-slate-400">{b.desc}</p></div><div className="grid size-12 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-cyan-300"><CreditCard/></div></div><ul className="mt-6 grid gap-3">{b.items.map(i=><li key={i} className="flex items-center gap-3 text-sm text-slate-300"><Check size={17} className="text-emerald-400"/>{i}</li>)}</ul><div className="mt-7"><ButtonLink href={b.href} target="_blank">{b.label} <ArrowRight size={16}/></ButtonLink></div></article>)}</div><p className="mt-8 text-xs leading-6 text-slate-600">A FiberStack apresenta as empresas sem recomendação ou preferência editorial. Taxas, preços e condições podem mudar. Alguns links podem gerar comissão sem custo adicional.</p></Container></section>;
}
