import Link from "next/link";
import {ArrowRight, BarChart3, Calculator, Check, CreditCard, ShieldCheck, Sparkles, Zap} from "lucide-react";
import {Container} from "@/components/layout/container";
import {ButtonLink} from "@/components/ui/button";

const tools=[
 {icon:CreditCard,title:"Comparador de maquininhas",text:"Compare taxas, recursos e recebimento.",href:"/comparador-maquininhas"},
 {icon:Calculator,title:"Calculadora de taxas",text:"Veja o custo real e o valor líquido.",href:"/calculadora-taxas"},
 {icon:Sparkles,title:"Ferramentas inteligentes",text:"Recursos para produtividade e vendas.",href:"/ferramentas"},
];
export default function Home(){return <>
<section className="relative min-h-[760px] overflow-hidden border-b border-white/[.07] py-20 sm:py-28"><div className="tech-grid"/><Container className="relative grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
<div><span className="inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/[.07] px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-emerald-300"><Sparkles size={14}/>Tecnologia que conecta</span><h1 className="mt-7 max-w-4xl text-5xl font-extrabold tracking-[-.055em] text-white sm:text-6xl lg:text-7xl">Ferramentas inteligentes <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-cyan-400 bg-clip-text text-transparent">para impulsionar seu negócio.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">Soluções práticas, calculadoras e comparativos para você tomar decisões melhores, economizar e vender mais.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/ferramentas" size="lg">Explorar ferramentas <ArrowRight size={18}/></ButtonLink><ButtonLink href="/comparador-maquininhas" variant="outline" size="lg">Ver maquininhas</ButtonLink></div>
<div className="mt-10 flex flex-wrap gap-5 text-sm text-slate-400">{["100% gratuito","Dados organizados","Foco em resultados"].map(x=><span key={x} className="inline-flex items-center gap-2"><Check size={16} className="text-emerald-400"/>{x}</span>)}</div></div>
<div className="relative mx-auto w-full max-w-[520px]"><div className="absolute inset-12 rounded-full bg-emerald-400/20 blur-[90px]"/><div className="glass glow-border relative rounded-[2.2rem] p-6 sm:p-8"><div className="absolute -right-4 -top-4 rounded-2xl border border-cyan-400/20 bg-[#07131b] p-4 text-cyan-300 shadow-2xl"><BarChart3/></div><div className="rounded-[1.7rem] border border-white/10 bg-[#04080c] p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Central FiberStack</p><h2 className="mt-2 text-2xl font-bold">Decisões melhores em um só lugar</h2></div><div className="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-emerald-400 to-cyan-500 text-[#03130c]"><Zap/></div></div><div className="mt-8 grid gap-3">{["Compare soluções","Calcule custos reais","Compare condições disponíveis"].map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-white/[.07] bg-white/[.035] p-4"><span className="grid size-8 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300">{i+1}</span><span className="font-medium text-slate-200">{x}</span></div>)}</div></div></div></div>
</Container></section>
<section className="py-20 sm:py-24"><Container><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-400">Comece por aqui</p><h2 className="mt-4 text-4xl font-bold tracking-[-.04em] sm:text-5xl">Tudo que você precisa para decidir melhor.</h2><p className="mt-4 text-lg text-slate-400">Ferramentas criadas para simplificar taxas, comparar soluções e acelerar seu negócio.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{tools.map(({icon:Icon,...t})=><Link href={t.href} key={t.title} className="glass group rounded-3xl p-7 transition hover:-translate-y-1 hover:border-emerald-400/30"><div className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-emerald-400/15 to-cyan-400/10 text-emerald-300"><Icon/></div><h3 className="mt-6 text-xl font-bold">{t.title}</h3><p className="mt-3 leading-7 text-slate-400">{t.text}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-emerald-300">Acessar <ArrowRight size={16}/></span></Link>)}</div></Container></section>
<section className="border-y border-white/[.07] bg-white/[.015] py-18"><Container className="grid gap-5 py-16 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Seguro","Informação clara"],[Zap,"Rápido","Resultados instantâneos"],[Calculator,"Prático","Simulações reais"],[BarChart3,"Estratégico","Compare antes de escolher"]].map(([I,t,d]:any)=><div key={t} className="text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-emerald-300"><I/></div><p className="mt-4 font-bold">{t}</p><p className="mt-1 text-sm text-slate-500">{d}</p></div>)}</Container></section>
<section className="py-20"><Container><div className="glow-border glass rounded-[2rem] px-7 py-14 text-center sm:px-12"><h2 className="text-3xl font-bold sm:text-5xl">Encontre a ferramenta certa para crescer.</h2><p className="mx-auto mt-5 max-w-2xl text-slate-400">Compare maquininhas e simule taxas com informações organizadas e neutras.</p><div className="mt-8"><ButtonLink href="/ferramentas" size="lg">Começar agora <ArrowRight size={18}/></ButtonLink></div></div></Container></section>
</>}
